name: learn-github-actions
on: [push]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: check linux kernel information
        run: uname -a
      - name: check pacman's version
        run: pacman -V 
