name: learn-github-actions
on: [push]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: check linux kernel version
        run: uname -r
